
---
- name: Add a tenant using a JSON string
  aci_rest:
    hostname: '{{ inventory_hostname }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    path: /api/mo/uni/tn-[{{ item.tenant_name }}].json
    method: post
    content: |
      {
        "fvTenant": {
           "attributes": {
             "name": "{{ item.tenant_name }}",
             "descr": "{{ item.tenant_name }}"
           }
         }
       }
  with_items: 
    - "{{ aci_tenant }}"
