---
  - name: ACI create tenant
    hosts: localhost

    vars_files:
      - aci_creds.yml

    tasks:    
      - name: Add a tenant using a JSON string
        aci_rest:
          hostname: '{{ inventory_hostname }}'
          username: '{{ aci_username }}'
          password: '{{ aci_password }}'
          validate_certs: no
          path: /api/mo/uni/tn-[DeleteMe].json
          method: post
          content: |
            {
              "fvTenant": {
                "attributes": {
                  "name": "DeleteMe",
                  "descr": "Delete Me"
                }
              }
            }
        delegate_to: localhost



