---
- name: Create ACI Application Profile
  aci_rest:
    hostname: '{{ apic_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    path: /api/mo/.json
    method: post
    content: |
      {
        "fvAp": {
          "attributes": {
            "descr": "", 
            "dn": "uni/tn-{{ item.tn_name }}/ap-{{ item.fvAp_name }}", 
            "name": "{{ item.fvAp_name }}", 
            "nameAlias": "", 
            "ownerKey": "", 
            "ownerTag": "", 
            "prio": "unspecified", 
            "status": "{{ item.status_is }}"
          }
        }
      }      
  with_items:
    - "{{ create_fvAp_vars }}"
